configfile: "config/config.yaml"
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

indir=config["input_namespace"]
outdir=config["output_namespace"]
params=config["params"]

rule target:
    input:
        url=HTTP.remote(params["url"])
    output:
        expand(
            "results/{outdir}/{filename}",
            outdir=outdir,
            filename=params["filename"]
        )
    log:
        f"benchmark/{outdir}.txt"
    benchmark:
        f"benchmark/{outdir}"
    conda:
        "envs/conda.yaml"
    shell:
        """
        mv {input} {output}
        """
