"""Plot a column from a data file (interactive)

This module plots a column from a data file. The source file and columns to plot on the x-axis and y-axis are specified in the modules' parameters. The plot remains on-screen until the user closes the plot, at which point the workflow will proceed. Data should be provided as a Comma-Separated-Variable (.csv) file.

Interactive: this module requires user interaction.

Params:
    Source (str): The source file to plot data from
    Column_X (str): The column to plot on the x-axis
    Column_Y (str): The column to plot on the y-axis
"""
configfile: "config/config.yaml"
from snakemake.remote import AUTO
import json

indir = config["input_namespace"]
outdir = config["output_namespace"]
params = config["params"]
filename = params["Source"]


def script(name=""):
    """Return the path to a script (detects local or remote execution modes)"""
    workflow_srcdir = srcdir("")
    try:
        from snakemake.remote import AUTO

        return AUTO.remote("/".join([workflow_srcdir, "scripts", name]))
    except TypeError:
        return Path(workflow_srcdir) / "scripts" / name


rule target:
    input:
        source=f"results/{indir}/{filename}",
        script=script("plotcol.py"),
    output:
        temp(touch(f"results/{outdir}/mark")),
    log:
        "logs/test.log"
    params:
        col_x=params["Column_X"],
        col_y=params["Column_Y"],
    conda:
        "envs/conda.yaml"
    shell:
        """
        python {input.script} \
            --source="{input.source}" \
            --col_x="{params.col_x}" \
            --col_y="{params.col_y}" \
        """
