"""Plot a column from a data file (interactive)

This module plots a column from a data file. The source file and columns to plot on the x-axis and y-axis are specified in the modules' parameters. The plot remains on-screen until the user closes the plot, at which point the workflow will proceed. Data should be provided as a Comma-Separated-Variable (.csv) file.

Interactive: this module requires user interaction.

Params:
    Source (str): The source file to plot data from
    Column_X (str): The column to plot on the x-axis
    Column_Y (str): The column to plot on the y-axis
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne
import json

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))


rule target:
    input:
        source=input(params("Source")),
        script=script("plotcol.py"),
    output:
        temp(touch(output("mark"))),
    log:
        log("test.log")
    params:
        col_x=params("Column_X"),
        col_y=params("Column_Y"),
    conda:
        env("conda.yaml")
    shell:
        """
        python {input.script} \
            --source="{input.source}" \
            --col_x="{params.col_x}" \
            --col_y="{params.col_y}" \
        """

rule _test:
    input:
        output("mark")
