"""Link to a local folder

The LocalFolder module has been replaced with CopyLocalFolder and LinkLocalFolder, which
provide more fine-grained control over file operations. It is recommended to use those
modules where possible. This module exists for backwards-compatbility.
"""
configfile: "config/config.yaml"
import configutil
config = configutil.remap_params(config)

module utility_linklocalfolder:
    snakefile:
        eval(
            f'{config["utility_linklocalfolder"]["snakefile"]["function"]}'
            '(*config["utility_linklocalfolder"]["snakefile"]["args"],'
            '**config["utility_linklocalfolder"]["snakefile"]["kwargs"])'
        )
    config:
        config["utility_linklocalfolder"]["config"]
use rule * from utility_linklocalfolder as utility_linklocalfolder_*
