configfile: "config/config.yaml"
from snakemake.remote import AUTO

indir=config["input_namespace"]
outdir=config["output_namespace"]
params=config["params"]

rule target:
    input:
        infile = expand(
            "results/{indir}/{filename}",
            indir=indir,
            filename=params["infile"],
        ),
        script = AUTO.remote(srcdir(f"../resources/scripts/test.sh")),
    output:
        expand(
            "results/{outdir}/{filename}",
            outdir=outdir,
            filename=params["outfile"],
        ),
    log:
        f"benchmark/{outdir}.log"
    benchmark:
        f"benchmark/{outdir}.txt"
    conda:
        "envs/conda.yaml"
    shell:
        """
        {input.script} {input.infile} {output}
        """
