"""Create an empty file

Create an empty file in the results directory with the name specified in the config file. This is often useful for providing triggers to downstream modules.

Params:
    Filename (str): The name of the file to create.
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne
from pathlib import Path

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))

rule touch:
    output:
        filename = output(params("Filename")),
    params:
        outdir = output(),
    run:
        Path(params.outdir).mkdir(parents=True, exist_ok=True)
        Path(output.filename).touch()

rule _test:
    input:
        output(params("Filename")),
