"""Get data from NCBI Sequence Database (genbank)

Retrieve sequence data from the National Centre for Biotechnology Information (NCBI)
Sequence Database (genbank). See https://www.ncbi.nlm.nih.gov/genbank/ for database
particulars.

Tags: genbank, database, ncbi, genbank

Params:
  Database (string): Database name ("nucleotide")
  ID: Idenitfier ("NC_001477")
  Return type (string): Return type ("fasta")
  Filename (string): Output filename ("seq.fasta")
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))


rule target:
    input:
        script=script("download_fasta.R"),
    output:
        output(param("Filename")),
    params:
        db = param("Database"),
        id = param("ID"),
        rettype = param("Return type"),
    log:
        log("genbank.log")
    conda:
        env("conda.yaml")
    shell:
        """
        RScript {input.script} \
            --db {params.db} \
            --id {params.id} \
            --rettype {params.rettype} \
            --output {output}
        """

rule _test:
    input:
        output(param("Filename")),
