"""Relative Wealth Index Preprocessing and aggregation

This module provides relative welath index preprocessing and aggregation functions,
producing a graphical plot which is also output as a png file.

Tags: relative-wealth-index, plot

Params:
    Root shape file (string): Filename for the root shape [.shp] file
    RWI file (string): Filename for the relative welath index [.csv] file
    Population file (string): Filename for the population [.csv] file
    Output image (string): Filename for the output map [.png] file
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))

rule target:
    input:
        shpfile=input(param("Root shape file"), "shape"),
        rwifile=input(param("RWI file"), "rwi"),
        popfile=input(param("Population file"), "pop"),
        script=script("rwi_proc_and_agg.py"),
    output:
        output(param("Output image"))
    params:
        gid_id=param("GID ID"),
    conda:
        env("conda.yaml")
    shell:
        """
        python {input.script} \
            --shpfile="{input.shpfile}" \
            --rwifile="{input.rwifile}" \
            --popfile="{input.popfile}" \
            --gid_id="{params.gid_id}" \
            --outfile="{output}"
        """
