"""BEASTgen

A simple program for transforming data from one format to another [https://beast.community/beastgen]. For example, change a NEXUS file into a FASTA file.

This module calls "beastgen [arguments] <template> <input> <output>" where arguments is a string of command line arguments. This can include the option ‘-D’ which allows the user to specify additional variables and their values that are specific to a BEASTGen operation (see https://beast.community/beastgen for more information). The template file is a BEASTGen template file that specifies how the input file should be transformed. The input file is the file to be transformed. The output file is the file that will be created by the transformation. Note that emplate and input files must be concrete (not symbolic links) for BEASTGen to work.

Params:
    Template filename (str): BEASTGen template file [concrete]
    Input filename (str): Input file [concrete]
    Output filename (str): Output file
    Arguments (str): Command line arguments
        See https://beast.community/beastgen for available options
"""
configfile: "config/config.yaml"

indir_template = config["input_namespace"]["template"]
indir_file = config["input_namespace"]["file"]
outdir = config["output_namespace"]

params = config["params"]
template_file = params["Template filename"]
in_file = params["Input filename"]
out_file = params["Output filename"]
arguments = params["Arguments"]

rule beastgen:
    input:
        infile = f"results/{indir_file}/{in_file}",
        template = f"results/{indir_template}/{template_file}",
    output:
        outfile = f"results/{outdir}/{out_file}",
    params:
        args = arguments,
    log:
        "logs/beastgen"
    conda:
        "envs/beastgen.yaml"
    shell:
        """
        # Download BEASTGen if not already present
        if [ ! -d resources ]; then
            mkdir -p resources/beastgen
            wget https://github.com/beast-dev/beast-mcmc/releases/download/v1.10.5pre_thorney_v0.1.2/BEASTGen_v0.3pre_thorney.tgz -O resources/beastgen.tgz
            tar -xzf resources/beastgen.tgz -C resources/beastgen --strip-components 1
            rm resources/beastgen.tgz
        fi

        # Run BEASTGen
        resources/beastgen/bin/beastgen {params.args} {input.template} {input.infile} {output.outfile}
        """
