"""Link a local file into the workflow

Links a local file and provides it as output.

Tags: utility, copy, files

Params:
    file (string): Path to file to copy
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne
import os

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))

# Get the full path to the target file
filename = params("File.Filename")
filepath = params("File.Folder")
fullfile = os.path.abspath(os.path.join(filepath, filename))

# Get the output directory and the relative path from that directory to the target
output_dir = os.path.abspath(output())
relpath = os.path.relpath(fullfile, output_dir)

rule copy:
    input:
        fullfile,
    output:
        outfile = output(filename),
    params:
        relpath = relpath,
    log:
        log(f"copy_{filename}.log"),
    shell:
        """
        ln -s -f {params.relpath} {output.outfile}
        """

rule _test:
    input:
        outfile = output(filename),
