"""Link a local file into the workflow

Links a local file and provides it as output.

Tags: utility, copy, files

Params:
    file (string): Path to file to copy
"""
configfile: "config/config.yaml"
import os

# Extract params from config file
outdir = config["output_namespace"]
params = config["params"]

# Get the full path to the target file
filename = params["File"]["Name"]
filepath = params["File"]["Folder"]
fullfile = os.path.abspath(os.path.join(filepath, filename))

# Get the output directory and the relative path from that directory to the target
output_dir = os.path.abspath(f"results/{outdir}")
relpath = os.path.relpath(fullfile, output_dir)

rule copy:
    input:
        fullfile,
    output:
        outfile = f"results/{outdir}/{filename}",
    params:
        relpath = relpath,
    conda:
        "envs/empty.yaml",
    log:
        f"logs/copy_{filename}.log",
    shell:
        """
        ln -s -f {params.relpath} {output.outfile}
        """
