"""Select columns from a data file

This module selects columns from a source file and writes them to a destination file.

Params:
    Source (str): The source file to read from
    Columns (list): The columns to select from the source file, e.g. "['col1', 'col2']"
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne
import json

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))


rule target:
    input:
        source=input(params("Source")),
        script=script("select_col.py"),
    output:
        output(params("Source")),
    log:
        "logs/test.log"
    params:
        cols=json.dumps(params("Columns")).replace("\"", "\'"),
    conda:
        env("conda.yaml")
    shell:
        """
        python {input.script} \
            --source="{input.source}" \
            --dest="{output}" \
            --cols="{params.cols}" \
        """

rule _test:
    input:
        infile = input(params("Source")),
        outfile = output(params("Source")),
    params:
        cols = params("Columns")
    run:
        # Source file has multiple columns
        with open(input.infile) as f:
            lines = f.readlines()
        assert len(lines[0].split(',')) > 2
        # Output file has only selected columns
        with open(input.outfile) as f:
            lines = f.readlines()
        header = lines[0].strip().split(',')
        assert len(header) == 2
        assert header[0] == params.cols[0]
        assert header[1] == params.cols[1]
