"""Remove annotations from a tree file
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))


rule remove_annotations:
    input:
        tree = input("timetree_{major_lineages}/timetree.nexus"),
    output:
        cleaned_tree = output("timetree_{major_lineages}/timetree.nexus"),
    log:
        log("remove_annotations_{major_lineages}.log")
    # container:
    #     "docker://evolbioinfo/gotree:v0.2.8b"
    conda:
        env("gotree.yaml")
    shell:
        """
        gotree comment clear \
            -i {input.tree} \
            --format nexus 1> {output.cleaned_tree} 2> {log}
        """


rule _test:
    input:
        output("timetree_Dengue_1/timetree.nexus"),
        output("timetree_Dengue_2/timetree.nexus"),
        output("timetree_Dengue_4/timetree.nexus"),

