input_namespace: "in"
output_namespace: "out"
params:
  trees: false
  decimal: false
  burnin: 100000
  resample: 10000
  scale: 1
  strip: false
  renumber: false
  input:
    infile1: "run-1.log"
    infile2: "run-2.log"
  output:
    outfile: "combined.log"