"""Copy a local file into the workflow

Makes a copy of a local file and provides it as output.

Tags: utility, copy, files

Params:
    file (string): Path to file to copy
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne
import os
import shutil

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))

filepath, filename = os.path.split(os.path.abspath(params("file")))

rule copy:
    input:
        params("file"),
    output:
        output(filename),
    run:
        shutil.copy(input[0], output[0])

rule _test:
    input:
        output(filename)
