"""Hello World!

This is a simple example module that demonstrates how to use GRAPEVNE modules. This module displays an image on the screen in a platform-independent way. The module touches an output file that we call a 'trigger' to signify that the module has completed successfully. The name of the trigger file is configurable.

Params:
    Triggers:
        Done (str): The name of the trigger file that will be touched when the module completes successfully.
"""
configfile: "config/config.yaml"
outdir = config["output_namespace"]
params = config["params"]
triggerfile = params["Triggers"]["Done"]


def resource(name=""):
    """Return the path to a resource payload (detects local or remote execution modes)"""
    workflow_srcdir = srcdir("")
    try:
        from snakemake.remote import AUTO

        return AUTO.remote("/".join([workflow_srcdir, "..", "resources", name]))
    except TypeError:
        return Path(workflow_srcdir) / ".." / "resources" / name


rule all:
    input:
        imgfile = resource("Hello.png")
    output:
        outfile = f"results/{outdir}/{triggerfile}"
    run:
        import sys
        import subprocess
        from pathlib import Path

        imageViewerFromCommandLine = {
            'linux':'xdg-open',
            'win32':'explorer',
            'darwin':'open'
        }[sys.platform]
        subprocess.run([imageViewerFromCommandLine, input.imgfile])
        Path(output.outfile).touch()

rule _test:
    input:
        outfile = f"results/{outdir}/{triggerfile}"
